name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Copy all necessary files into deploy/
        run: |
          mkdir -p deploy
          # Copy all files from the root to deploy (excluding workflows, etc.)
          rsync -av --exclude='deploy/' --exclude='.github/' --exclude='.git/' --exclude='.gitignore' --exclude='README.md' --exclude='_config.yml' ./ ./deploy/

      - name: Minify all .json files in deploy/
        run: |
          find deploy -name '*.json' | while read file; do
            jq -c . "$file" > tmp.json && mv tmp.json "$file"
          done

      - name: Minify and round coordinates in .geojson files in deploy/
        run: |
          find deploy -name '*.geojson' | while read file; do
            jq 'def r: if type=="array" then map(r) elif type=="object" then with_entries(.value |= r) elif type=="number" then (.*100000|round)/100000 else . end;
                . as $in
                | if has("features") then
                    .features |= map(
                      if has("geometry") and .geometry.coordinates then
                        .geometry.coordinates |= (r)
                      else . end
                    )
                  elif has("geometry") and .geometry.coordinates then
                    .geometry.coordinates |= (r)
                  else . end' "$file" > tmp.geojson && mv tmp.geojson "$file"
          done

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          force_orphan: true
          skip_publish: true
